# roles/aws/elb/tasks/main.yml
---
# create elb and atttach healthy instances to it

- name: Create the ELB only listening over port 80
  ec2_elb_lb:
    name: ansible-lb
    state: present
    region: "{{ aws_region }}"
    subnets: [ "{{ vpc_subnet_ids[item] }}" ]
    security_group_names: [ 'vpc', 'allow-public-http', 'allow-public-ssh']
    listeners:
      - protocol: http
        load_balancer_port: 80
        instance_port: 80
    health_check:
        ping_protocol: tcp # options are http, https, ssl, tcp
        ping_port: 80 # not required for tcp or ssl
        response_timeout: 5 # seconds
        interval: 20 # seconds
        unhealthy_threshold: 5
        healthy_threshold: 10
  register: elb
  with_items: [public-a, public-b]

- name: Add each EC2 instance to the ELB
  ec2_elb:
    state: present
    ec2_elbs: ansible-lb
    region: "{{ aws_region }}"
    instance_id: "{{ item.1.id }}"
    wait: yes
    wait_timeout: 500
  with_subelements:
    - "{{ ec2.results }}"
    - tagged_instances