# create ec2 instances
---
# for single creation of instance only
- name: Create Public EC2 instances
  ec2:
    key_name: "{{ key_name }}"
    region: "{{ region }}"
    instance_type: "{{ instance_type }}"
    image: "{{ image }}"
    vpc_subnet_id: "{{ vpc_subnet_id }}"
    assign_public_ip: "{{ assign_public_ip }}"
    count_tag: "{{ count_tag }}"
    exact_count: "{{ exact_count }}"
    group: "{{ group }}"
    wait: true
  register: ec2

- name: Add EC2 IP as host
  add_host:
    hostname: "{{ item.public_ip }}"
    groupname: webserver
    host_key_checking: = False
  with_items: "{{ ec2.instances }}"

- name: Add tag to Instance(s)
  ec2_tag:
    resource: "{{ item.id }}" 
    region: "{{ region }}" 
    state: "present"
  with_items: "{{ ec2.instances }}"
  args:
    tags:
      Type: webserver

- name: Wait for SSH to come up
  wait_for:
    host: "{{ item.public_ip }}"
    port: 22 
    state: started 
  with_items: "{{ ec2.instances }}"