---
#roles/create_ec2/vars/main.yml
#Assign parameters as variables for creation of EC2 Instances

# a map defining the subnets we will build in the VPC
key_name: "{{ key }}"
region: "{{ region }}"
image: ami-026c8acd92718196b
instance_type: t2.micro

my_ec2:
  private-a:
    vpc_subnet_id: "{{ vpc_subnet_ids['private-a'] }}"
    assign_public_ip: no
    group: allow-public-ssh
    count_tag: private-a
    exact_count: 1
    instance_tags:
      Subnet: private-a 
  private-b:
    vpc_subnet_id: "{{ vpc_subnet_ids['private-b'] }}"
    assign_public_ip: no
    group: allow-public-ssh
    count_tag: private-b
    exact_count: 2
    instance_tags:
      Subnet: private-a
  public-a:
    vpc_subnet_id: "{{ vpc_subnet_ids['public-a'] }}"
    assign_public_ip: yes
    group: vpc
    count_tag: public-a
    exact_count: 1
    instance_tags:
      Subnet: public-a 
  public-b:
    vpc_subnet_id: "{{ vpc_subnet_ids['public-b'] }}"
    assign_public_ip: yes
    group: vpc
    count_tag: public-b
    exact_count: 2
    instance_tags:
      Subnet: public-a 


