# roles/deploy/nginx/tasks/main.yml
---
# install nginx and create index page
- name: Install nginx
  apt:
    name: nginx
    state: present
- name: Create default index page
  copy:
    dest: /usr/share/nginx/html/index.html
    content: "Howdy from {{ ansible_hostname }}"
- name: Restart nginx
  service:
    name: nginx
    state: restarted