# roles/aws/vpc/vars/main.yml
---
# vars file for creation of vpc, subnet, sg
# for sample purposes (only 1 private and 1 public subnet)

# general details about our VPC
vpc_name: ansible
vpc_key: ansible

# IP CIDR block for the VPC
vpc_cidr_block: 10.0.0.0/16

# a map defining the subnets we will build in the VPC
vpc_subnets:
  private-a:
    cidr: 10.0.1.0/24
    az: "{{ aws_region }}a"
  public-a:
    cidr: 10.0.2.0/24
    az: "{{ aws_region }}a"

# a list defining the security groups for our VPC
vpc_security_groups:
  - name: vpc
    description: "Allow internal traffic in the VPC"
    rules:
      - proto: all
        group_name: vpc
        ports: 
          - 22
          - 80
          - 3306
  - name: allow-public-ssh
    description: "Allow public SSH"
    rules:
      - proto: tcp
        cidr_ip: 0.0.0.0/0
        ports:
          - 22
  - name: allow-public-http
    description: "Allow public web traffic"
    rules:
      - proto: tcp
        cidr_ip: 0.0.0.0/0
        ports:
          - 80
          - 8080
          - 443
